openapi: 3.1.0
info:
  version: 0.1.0
  title: TogoMedium API
  contact:
    url: https://togomedium.org
  x-logo:
    url: "https://redocly.github.io/openapi-template/logo.png"
    altText: OpenAPI example logo
  description: >
    TODO: write description
security:
  - {}
tags:
  - name: List Stanza
    description: "Example echo operations."
x-tagGroups:
  - name: General
    tags:
      - List Stanza
servers:
  - url: https://togomedium.org/sparqlist/api
    description: "TogoMedium SPARQList API server"
paths:
  /gmdb_infraspecific_list_by_taxid:
    $ref: "paths/list/gmdb_infraspecific_list_by_taxid.yaml"
  /gmdb_list_components_by_gmoids:
    $ref: "paths/list/gmdb_list_components_by_gmoids.yaml"
  /gmdb_list_components_by_keyword:
    $ref: "paths/list/gmdb_list_components_by_keyword.yaml"
  /gmdb_list_media:
    $ref: "paths/list/gmdb_list_media.yaml"
  /gmdb_list_media_by_gmids:
    $ref: "paths/list/gmdb_list_media_by_gmids.yaml"
