openapi: 3.0.0
info:
  title: Growth Medium API
  description: |
    # これは何？
    TogoMedium データベースを検索するためのAPI集
    # 表記ルール
    * **IDの記述法**<br>
    `xxx-id` `xxx-ids` の方式に統一する。<br>
    従来から存在しているSPAQList内では`gmoid`等、区切りの扱いが統一されていないものがあるがあるので注意が必要。
  version: "1"
servers:
  - url: http://growthmedium.org/sparqlist/api/
paths:
  /gmdb_media_by_taxon/:
    $ref: "core/media-by-taxon.yaml"
  /gmdb_organisms_by_phenotypes/:
    $ref: "core/organisms-by-phenotypes.yaml"
  /gmdb_media_by_attributes/:
    $ref: "core/media-by-attributes.yaml"
  /gmdb_media_alignment_by_gmids/:
    $ref: "core/media-alignment-table.yaml"
  /gmdb_all_components/:
    $ref: "core/all-components.yaml"
  /gmdb_taxonomy_children/:
    $ref: "core/taxonomy-children.yaml"
