openapi: 3.0.0
info:
  title: Growth Medium API
  description: |
    # これは何？
    TogoMedium データベースを検索するためのAPI集
    # 表記ルール
    * **IDの記述法**<br>
    `xxx_id` `xxx_ids` の方式に統一する。<br>
    従来から存在しているSPAQList内では`gmoid`等、区切りの扱いが統一されていないものがあるがあるので注意が必要。
  version: "1"
servers:
  - url: http://growthmedium.org/sparqlist/api/
tags:
  - name: Y2021
  - name: Media Finder
  - name: Alignment Table
  - name: List Stanza
  - name: Stanza
  - name: Unused

x-tagGroups:
  - name: API
    tags:
      - Y2021
      - Media Finder
      - Stanza
      - List Stanza
      - Unused
paths:
  /gmdb_media_by_taxon/:
    $ref: "paths/y2021/media_by_taxon.yaml"
  /gmdb_organisms_by_phenotypes/:
    $ref: "paths/y2021/organisms_by_phenotypes.yaml"
  /gmdb_media_by_attributes/:
    $ref: "paths/y2021/media_by_attributes.yaml"
  /gmdb_media_alignment_by_gm_ids/:
    $ref: "paths/y2021/media_alignment-table.yaml"
  /gmdb_all_components/:
    $ref: "paths/y2021/all_components.yaml"
  /gmdb_taxonomy_children/:
    $ref: "paths/y2021/taxonomy_children.yaml"
  /adjacent_prefectures:
    get:
      summary: adjacent_prefectures
      tags:
        - Unused
      responses:
        200:
          description: Unknown
  /gene_and_organism_annotation:
    get:
      summary: gene_and_organism_annotation
      tags:
        - Unused
      responses:
        200:
          description: Unknown
  /gmdb_component_by_gmoid:
    get:
      summary: gmdb_component_by_gmoid
      description: >
        コンポーネント詳細ページで使用
      tags:
        - Stanza
      responses:
        200:
          description: SUCCESS
  /gmdb_infraspecific_list_by_taxid:
    get:
      summary: gmdb_infraspecific_list_by_taxid
      description: >
        タクソン詳細ページで使用<br>
        タクソンに含まれる生物種をリストアップする
      tags:
        - List Stanza
      responses:
        200:
          description: List Stanza
  /gmdb_list_components_by_gmoids:
    get:
      summary: gmdb_list_components_by_gmoids
      description: >
        自由検索で使用<br>
        GMO_IDを元にコンポーネントをリストアップする
      tags:
        - List Stanza
      responses:
        200:
          description: SUCCESS
  /gmdb_list_components_by_keyword:
    get:
      summary: gmdb_list_components_by_keyword
      description: >
        自由検索で使用<br>
        キーワードを元にコンポーネントをリストアップする
      tags:
        - List Stanza
      responses:
        200:
          description: SUCCESS
  /gmdb_list_media:
    get:
      deprecated: true
      summary: gmdb_list_media
      description: >
        `list_media` と機能被り？サイト上では不使用
      tags:
        - Unused
      responses:
        200:
          description: Unknown
  /gmdb_list_media_by_gmids:
    get:
      summary: gmdb_list_media_by_gmids
      description: >
        自由検索で使用<br>
        GMIDを元に培地をリストアップする
      tags:
        - List Stanza
      responses:
        200:
          description: SUCCESS
  /gmdb_list_media_by_keyword:
    get:
      summary: gmdb_list_media_by_keyword
      description: >
        自由検索で使用<br>
        キーワードを元に培地をリストアップする
      tags:
        - List Stanza
      responses:
        200:
          description: SUCCESS
  /gmdb_list_organisms_by_keyword:
    get:
      summary: gmdb_list_organisms_by_keyword
      description: >
        自由検索で使用<br>
        キーワードを元に生物をリストアップする
      tags:
        - List Stanza
      responses:
        200:
          description: SUCCESS
  /gmdb_list_organisms_by_keywords:
    get:
      deprecated: true
      summary: gmdb_list_organisms_by_keywords
      description: >
        List Stanza導入前に使用していた
      tags:
        - Unused
      responses:
        200:
          description: DEPRECATED
  /gmdb_list_organisms_by_taxids:
    get:
      summary: gmdb_list_organisms_by_taxids
      description: >
        自由検索で使用<br>
        TAX_IDを元に生物をリストアップする
      tags:
        - List Stanza
      responses:
        200:
          description: SUCCESS
  /gmdb_list_similar_media_by_gmid:
    get:
      summary: gmdb_list_similar_media_by_gmid
      description: >
        培地詳細で使用<br>
        GM_IDを元に似た培地をリストアップする
      tags:
        - List Stanza
      responses:
        200:
          description: SUCCESS
  /gmdb_media_by_gmoid:
    get:
      summary: gmdb_media_by_gmoid
      description: >
        コンポーネント詳細で使用<br>
        GMO_IDを元に紐付いた培地をリストアップする
      tags:
        - List Stanza
      responses:
        200:
          description: SUCCESS
  /gmdb_media_by_gmoid_okbp:
    get:
      summary: gmdb_media_by_gmoid_okbp
      description: >
        岡別府さんの検証用？
      tags:
        - Unused
      responses:
        200:
          description: Unknown
  /gmdb_media_by_rank:
    get:
      summary: gmdb_media_by_rank
      description: >
        Unknown
      tags:
        - Unused
      responses:
        200:
          description: Unknown
  /gmdb_media_by_taxid:
    get:
      summary: gmdb_media_by_taxid
      description: >
        生物種及びタクソン詳細ページで使用。<br>
        TAX_IDを元に紐付いた培地をリストアップする
      tags:
        - List Stanza
      responses:
        200:
          description: SUCCESS
  /gmdb_medium_by_gmid:
    get:
      summary: gmdb_medium_by_gmid
      description: >
        培地の詳細を返す
      tags:
        - Stanza
      responses:
        200:
          description: SUCCESS
  /gmdb_medium_by_gmid__TEST:
    get:
      summary: gmdb_medium_by_gmid__TEST
      description: >
        誰かのテスト用？
      tags:
        - Unused
      responses:
        200:
          description: Unknown
  /gmdb_organism_by_taxid:
    get:
      summary: gmdb_organism_by_taxid
      description: >
        生物の詳細を返す
      tags:
        - Stanza
      responses:
        200:
          description: SUCCESS
  /gmdb_organism_by_taxid_okbp:
    get:
      summary: gmdb_organism_by_taxid_okbp
      description: >
        岡別府さんの検証用？
      tags:
        - Unused
      responses:
        200:
          description: Unknown
  /gmdb_organisms_by_gmid:
    get:
      summary: gmdb_organisms_by_gmid
      description: >
        培地ページで使用。<br>
        GM_IDを元に紐付いた生物種をリストアップする
      tags:
        - List Stanza
      responses:
        200:
          description: SUCCESS
  /gmdb_stat_phylum_gm:
    get:
      summary: gmdb_stat_phylum_gm
      description: >
        Statisticsページで使用。<br>
        Phylumごとに対応する培地の統計をリストアップする
      tags:
        - List Stanza
      responses:
        200:
          description: SUCCESS
  /gmdb_taxonomic_rank_by_taxid:
    get:
      summary: gmdb_taxonomic_rank_by_taxid
      description: >
        タクソンの詳細を返す
      tags:
        - Stanza
      responses:
        200:
          description: SUCCESS
  /gms_by_kegg_tids_3:
    get:
      summary: gms_by_kegg_tids_3
      description: >
        Alignmentページで使用
      tags:
        - Stanza
      responses:
        200:
          description: SUCCESS
  /gms_kegg_code_tid:
    get:
      summary: gms_kegg_code_tid
      description: >
        Alignmentページで使用
      tags:
        - Stanza
      responses:
        200:
          description: SUCCESS
  /interview-form-ex2-mod:
    get:
      summary: interview-form-ex2-mod
      tags:
        - Unused
      responses:
        200:
          description: Unknown
  /list_components:
    get:
      summary: list_components
      description: >
        コンポーネント一覧をリストアップする
      tags:
        - List Stanza
      responses:
        200:
          description: SUCCESS
  /list_media:
    get:
      summary: list_media
      description: >
        培地一覧をリストアップする
      tags:
        - List Stanza
      responses:
        200:
          description: SUCCESS
  /list_organisms:
    get:
      summary: list_organisms
      description: >
        生物種一覧をリストアップする
      tags:
        - List Stanza
      responses:
        200:
          description: SUCCESS
  /list_taxons_by_rank:
    get:
      summary: list_taxons_by_rank
      description: >
        トップページで使用<br>
        TAX_ID以下にある指定した階層のタクソン/生物種を返す
      tags:
        - Stanza
      responses:
        200:
          description: SUCCESS
