openapi: 3.0.0
info:
  title: Growth Medium API
  description: |
    # これは何？
    TogoMedium データベースを検索するためのAPI集
    # 表記ルール
    * **IDの記述法**<br>
    `xxx_id` `xxx_ids` の方式に統一する。<br>
    従来から存在しているSPAQList内では`gmoid`等、区切りの扱いが統一されていないものがあるがあるので注意が必要。
  version: "1"
servers:
  - url: http://growthmedium.org/sparqlist/api/
tags:
  - name: Y2021
  - name: Media Finder
  - name: Alignment Table
  - name: List Stanza
  - name: Stanza
  - name: Unused

x-tagGroups:
  - name: API
    tags:
      - Y2022
      - Y2021
      - Media Finder
      - Stanza
      - List Stanza
      - Unused
paths:
  /gmdb_components_with_components/:
    $ref: "paths/y2022/components_with_components.yaml"
  /gmdb_gmdb_media_organisms_alignment_by_gm_ids/:
    $ref: "paths/y2022/media_strains_alignment_table.yaml"
  /gmdb_media_by_taxon/:
    $ref: "paths/y2021/media_by_taxon.yaml"
  /gmdb_organisms_by_phenotypes/:
    $ref: "paths/y2021/organisms_by_phenotypes.yaml"
  /gmdb_media_by_attributes/:
    $ref: "paths/y2021/media_by_attributes.yaml"
  /gmdb_media_alignment_by_gm_ids/:
    $ref: "paths/y2021/media_alignment-table.yaml"
  /gmdb_all_components/:
    $ref: "paths/y2021/all_components.yaml"
  /gmdb_taxonomy_children/:
    $ref: "paths/y2021/taxonomy_children.yaml"
  #####
  /gmdb_component_by_gmoid:
    $ref: "paths/stanza/gmdb_component_by_gmoid.yaml"
  /gmdb_medium_by_gmid:
    $ref: "paths/stanza/gmdb_medium_by_gmid.yaml"
  /gmdb_organism_by_taxid:
    $ref: "paths/stanza/gmdb_organism_by_taxid.yaml"
  /gmdb_taxonomic_rank_by_taxid:
    $ref: "paths/stanza/gmdb_taxonomic_rank_by_taxid.yaml"
  /gms_by_kegg_tids_3:
    $ref: "paths/stanza/gms_by_kegg_tids_3.yaml"
  /gms_kegg_code_tid:
    $ref: "paths/stanza/gms_kegg_code_tid.yaml"
  /list_taxons_by_rank:
    $ref: "paths/stanza/list_taxons_by_rank.yaml"
  #####
  /gmdb_infraspecific_list_by_taxid:
    $ref: "paths/list/gmdb_infraspecific_list_by_taxid.yaml"
  /gmdb_list_components_by_gmoids:
    $ref: "paths/list/gmdb_list_components_by_gmoids.yaml"
  /gmdb_list_components_by_keyword:
    $ref: "paths/list/gmdb_list_components_by_keyword.yaml"
  /gmdb_list_media:
    $ref: "paths/list/gmdb_list_media.yaml"
  /gmdb_list_organisms_by_keywords:
    $ref: "paths/list/gmdb_list_organisms_by_keywords.yaml"
  /gmdb_list_media_by_gmids:
    $ref: "paths/list/gmdb_list_media_by_gmids.yaml"
  /gmdb_list_media_by_keyword:
    $ref: "paths/list/gmdb_list_media_by_keyword.yaml"
  /gmdb_list_organisms_by_keyword:
    $ref: "paths/list/gmdb_list_organisms_by_keyword.yaml"
  /gmdb_list_organisms_by_taxids:
    $ref: "paths/list/gmdb_list_organisms_by_taxids.yaml"
  /gmdb_list_similar_media_by_gmid:
    $ref: "paths/list/gmdb_list_similar_media_by_gmid.yaml"
  /gmdb_media_by_gmoid:
    $ref: "paths/list/gmdb_media_by_gmoid.yaml"
  /gmdb_media_by_taxid:
    $ref: "paths/list/gmdb_media_by_taxid.yaml"
  /gmdb_organisms_by_gmid:
    $ref: "paths/list/gmdb_organisms_by_gmid.yaml"
  /gmdb_stat_phylum_gm:
    $ref: "paths/list/gmdb_stat_phylum_gm.yaml"
  /list_components:
    $ref: "paths/list/list_components.yaml"
  /list_media:
    $ref: "paths/list/list_media.yaml"
  /list_organisms:
    $ref: "paths/list/list_organisms.yaml"
  #####
  /adjacent_prefectures:
    get:
      summary: adjacent_prefectures
      tags:
        - Unused
      responses:
        200:
          description: Unknown
  /gene_and_organism_annotation:
    get:
      summary: gene_and_organism_annotation
      tags:
        - Unused
      responses:
        200:
          description: Unknown
  /gmdb_media_by_gmoid_okbp:
    get:
      summary: gmdb_media_by_gmoid_okbp
      description: >
        岡別府さんの検証用？
      tags:
        - Unused
      responses:
        200:
          description: Unknown
  /gmdb_media_by_rank:
    get:
      summary: gmdb_media_by_rank
      description: >
        Unknown
      tags:
        - Unused
      responses:
        200:
          description: Unknown
  /gmdb_medium_by_gmid__TEST:
    get:
      summary: gmdb_medium_by_gmid__TEST
      description: >
        誰かのテスト用？
      tags:
        - Unused
      responses:
        200:
          description: Unknown
  /gmdb_organism_by_taxid_okbp:
    get:
      summary: gmdb_organism_by_taxid_okbp
      description: >
        岡別府さんの検証用？
      tags:
        - Unused
      responses:
        200:
          description: Unknown
  /interview-form-ex2-mod:
    get:
      summary: interview-form-ex2-mod
      tags:
        - Unused
      responses:
        200:
          description: Unknown
